#  vim: set et fenc=utf-8 ff=unix sts=2 sw=2 ts=2 :
version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    #volumes:
      #- ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    #ports:
      #- "9200:9200"
      #- "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logs:/logs:ro
    #ports:
      #- "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
